/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as HoneypotsRouteImport } from './routes/honeypots'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreatIntelRouteImport } from './routes/threat-intel'
import { Route as AttackersIpRouteImport } from './routes/attackers/$ip'
import { Route as EvaluationIndexRouteImport } from './routes/evaluation/index'
import { Route as EvaluationRunIdRouteImport } from './routes/evaluation/$runId'
import { Route as EvaluationCompareRouteImport } from './routes/evaluation/compare'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneypotsRoute = HoneypotsRouteImport.update({
  id: '/honeypots',
  path: '/honeypots',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackersIpRoute = AttackersIpRouteImport.update({
  id: '/attackers/$ip',
  path: '/attackers/$ip',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationIndexRoute = EvaluationIndexRouteImport.update({
  id: '/evaluation/',
  path: '/evaluation/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRunIdRoute = EvaluationRunIdRouteImport.update({
  id: '/evaluation/$runId',
  path: '/evaluation/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationCompareRoute = EvaluationCompareRouteImport.update({
  id: '/evaluation/compare',
  path: '/evaluation/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/honeypots': typeof HoneypotsRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/attackers/$ip': typeof AttackersIpRoute
  '/evaluation/$runId': typeof EvaluationRunIdRoute
  '/evaluation/compare': typeof EvaluationCompareRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/evaluation/': typeof EvaluationIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/honeypots': typeof HoneypotsRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/attackers/$ip': typeof AttackersIpRoute
  '/evaluation/$runId': typeof EvaluationRunIdRoute
  '/evaluation/compare': typeof EvaluationCompareRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/evaluation': typeof EvaluationIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/honeypots': typeof HoneypotsRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/attackers/$ip': typeof AttackersIpRoute
  '/evaluation/$runId': typeof EvaluationRunIdRoute
  '/evaluation/compare': typeof EvaluationCompareRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/evaluation/': typeof EvaluationIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/honeypots'
    | '/logs'
    | '/mitre'
    | '/reports'
    | '/settings'
    | '/threat-intel'
    | '/attackers/$ip'
    | '/evaluation/$runId'
    | '/evaluation/compare'
    | '/sessions/$sessionId'
    | '/evaluation/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/honeypots'
    | '/logs'
    | '/mitre'
    | '/reports'
    | '/settings'
    | '/threat-intel'
    | '/attackers/$ip'
    | '/evaluation/$runId'
    | '/evaluation/compare'
    | '/sessions/$sessionId'
    | '/evaluation'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/honeypots'
    | '/logs'
    | '/mitre'
    | '/reports'
    | '/settings'
    | '/threat-intel'
    | '/attackers/$ip'
    | '/evaluation/$runId'
    | '/evaluation/compare'
    | '/sessions/$sessionId'
    | '/evaluation/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  HoneypotsRoute: typeof HoneypotsRoute
  LogsRoute: typeof LogsRoute
  MitreRoute: typeof MitreRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
  AttackersIpRoute: typeof AttackersIpRoute
  EvaluationRunIdRoute: typeof EvaluationRunIdRoute
  EvaluationCompareRoute: typeof EvaluationCompareRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  EvaluationIndexRoute: typeof EvaluationIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honeypots': {
      id: '/honeypots'
      path: '/honeypots'
      fullPath: '/honeypots'
      preLoaderRoute: typeof HoneypotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intel': {
      id: '/threat-intel'
      path: '/threat-intel'
      fullPath: '/threat-intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attackers/$ip': {
      id: '/attackers/$ip'
      path: '/attackers/$ip'
      fullPath: '/attackers/$ip'
      preLoaderRoute: typeof AttackersIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/': {
      id: '/evaluation/'
      path: '/evaluation'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof EvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/$runId': {
      id: '/evaluation/$runId'
      path: '/evaluation/$runId'
      fullPath: '/evaluation/$runId'
      preLoaderRoute: typeof EvaluationRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/compare': {
      id: '/evaluation/compare'
      path: '/evaluation/compare'
      fullPath: '/evaluation/compare'
      preLoaderRoute: typeof EvaluationCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  HoneypotsRoute: HoneypotsRoute,
  LogsRoute: LogsRoute,
  MitreRoute: MitreRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelRoute: ThreatIntelRoute,
  AttackersIpRoute: AttackersIpRoute,
  EvaluationRunIdRoute: EvaluationRunIdRoute,
  EvaluationCompareRoute: EvaluationCompareRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  EvaluationIndexRoute: EvaluationIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
