import { Bot, Eye, GitCompareArrows, Microscope, FlaskConical } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Provenance } from "@/types";

const STYLES: Record<Provenance, { className: string; Icon: typeof Eye; hint: string }> = {
  OBSERVED: {
    className: "border-success/40 bg-success/12 text-success",
    Icon: Eye,
    hint: "Recorded directly in honeypot telemetry.",
  },
  "AI INFERENCE": {
    className: "border-ai/40 bg-ai/12 text-ai",
    Icon: Bot,
    hint: "Generated by the LLM. Verify against the evidence below.",
  },
  CORRELATED: {
    className: "border-info/40 bg-info/12 text-info",
    Icon: GitCompareArrows,
    hint: "Derived by correlating multiple sessions or sensors.",
  },
  "STATIC ANALYSIS": {
    className: "border-medium/40 bg-medium/12 text-medium",
    Icon: Microscope,
    hint: "Produced by static inspection of a captured artefact.",
  },
};

export function ProvenanceBadge({
  kind,
  className,
  showIcon = true,
}: {
  kind: Provenance;
  className?: string;
  showIcon?: boolean;
}) {
  const style = STYLES[kind];
  const { Icon } = style;
  return (
    <span
      title={style.hint}
      className={cn(
        "inline-flex items-center gap-1.5 rounded border px-1.5 py-[3px] font-mono text-[10px] font-semibold uppercase tracking-[0.08em] leading-none whitespace-nowrap",
        style.className,
        className,
      )}
    >
      {showIcon ? <Icon className="size-3" aria-hidden /> : null}
      {kind}
    </span>
  );
}

/** Marks synthetic dataset output so demo data is never mistaken for a backend response. */
export function DemoDataBadge({ className }: { className?: string }) {
  return (
    <span
      title="Synthetic dataset served by DemoProvider. Not a backend or LLM response."
      className={cn(
        "inline-flex items-center gap-1.5 whitespace-nowrap rounded border border-border-strong bg-muted/60 px-1.5 py-[3px] font-mono text-[10px] font-semibold uppercase tracking-[0.08em] leading-none text-muted-foreground",
        className,
      )}
    >
      <FlaskConical className="size-3" aria-hidden />
      Demo data
    </span>
  );
}
